version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mediflow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mediflow
      POSTGRES_PASSWORD: mediflow123
      POSTGRES_DB: mediflow
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
